### ISSUE TITLE
Add precommit-hooks to automatically check code formatting. 

### ISSUE THREAD

**Issue by zakajd** [photosynthesis-team/piq#271]
**Is your feature request related to a problem? Please describe.**
Currently we have flake8, mypy and other code checkers running in our CI, but code format is not checked on user side. 

**Describe the solution you'd like**
Use `precommit-hooks` library to force check code style **before** commit on user side, to make development process easier.  

**Additional context**
Example of simple pre-commit file that should work
```yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      # list of supported hooks: https://pre-commit.com/hooks.html
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: debug-statements
      - id: detect-private-key

  # python code formatting
  - repo: https://github.com/psf/black
    rev: 21.8b0
    hooks:
      - id: black
        args: [--line-length, "120"]

  # python code analysis
  - repo: https://github.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        args: ["--max-line-length", "120"]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: ''  # Use the sha / tag you want to point at
    hooks:
    -   id: mypy
      args: [--no-strict-optional, --ignore-missing-imports]
```

**How to use it**
Install pre-commit package with:
```bash
pip install pre-commit
```
Next, install hooks from [.pre-commit-config.yaml](.pre-commit-config.yaml):
```bash
pre-commit install
```
After that your code will be automatically reformatted on every new commit.<br>

To format all files in the project use command:
```bash
pre-commit run -a
```
